# Site settings
title: System-on-Chip Design & Verification
author:
  name: Daragh Kearney
  email: g00438215@atu.ie
description: "Minecraft Steve Blog."

# Build settings
remote_theme: jekyll/minima
